import { roundAndAddZeros } from "./product.module.js";

export const totals = {
  pricing: roundAndAddZeros(0, 4),
  volume: roundAndAddZeros(0, 4),
  products: 0,
  customerSites: 0,
  warehousePrice: roundAndAddZeros(0, 4),
  flete: roundAndAddZeros(0, 4),
  labTransfer: roundAndAddZeros(0, 4),
  shareholders: roundAndAddZeros(0, 4),
  productCost: roundAndAddZeros(0, 4),
  railroad: roundAndAddZeros(0, 4),
  operativeAlmidon: roundAndAddZeros(0, 4),
  operativePacking: roundAndAddZeros(0, 4),
  totalBuildCost: roundAndAddZeros(0, 4),
  profitMarginPercentage: roundAndAddZeros(0, 4),
  profitMargin: roundAndAddZeros(0, 4),
  totalProductCost: roundAndAddZeros(0, 4),
  isotank: roundAndAddZeros(0, 4),
  clientPortals: roundAndAddZeros(0, 4),
  dryStorage: roundAndAddZeros(0, 4),
  totalOperativeCost: roundAndAddZeros(0, 4),
  totalSalesCost: roundAndAddZeros(0, 4),
  marginBrute: roundAndAddZeros(0, 4),
  marginBruteNetSales: roundAndAddZeros(0, 4),
  overhead: roundAndAddZeros(0, 4),
  marginBeforeTaxes: roundAndAddZeros(0, 4),
  netMarginBeforeSales: roundAndAddZeros(0, 4),
  ptu: roundAndAddZeros(0, 4),
  isr: roundAndAddZeros(0, 4),
  netMargin: roundAndAddZeros(0, 4),
  incrementalCostPercentage: roundAndAddZeros(0, 4),
  incrementalCostRebate: roundAndAddZeros(0, 4),
  exwIncrementals: roundAndAddZeros(0, 4),
  finantialCostPercentage: roundAndAddZeros(0, 4),
  finantialCost: roundAndAddZeros(0, 4),
  exwFinantialCost: roundAndAddZeros(0, 4),
};