public with sharing class QuoteItemModel {
	@AuraEnabled
	public String billedPrice { get; set; }
	@AuraEnabled
	public String productId { get; set; }
	@AuraEnabled
	public String volume { get; set; }
	@AuraEnabled
	public String totalProductCost { get; set; }
	@AuraEnabled
	public String storage { get; set; }
	@AuraEnabled
	public String customerSiteName { get; set; }
	@AuraEnabled
	public String almexPriceWarehouse { get; set; }
	@AuraEnabled
	public String transportation { get; set; }
	@AuraEnabled
	public String tons { get; set; }
	@AuraEnabled
	public String deliveryCost { get; set; }
	@AuraEnabled
	public String labTransferPrice { get; set; }
	@AuraEnabled
	public String productShareholdersCost { get; set; }
	@AuraEnabled
	public String productCost { get; set; }
	@AuraEnabled
	public String railroadCost { get; set; }
	@AuraEnabled
	public String importExpensesAlmidon { get; set; }
	@AuraEnabled
	public String transferImportExpPacking { get; set; }
	@AuraEnabled
	public String totalBuildingCost { get; set; }
	@AuraEnabled
	public String profitMarginPercentage { get; set; }
	@AuraEnabled
	public String isotank { get; set; }
	@AuraEnabled
	public String clientPortals { get; set; }
	@AuraEnabled
	public String storageDry { get; set; }
	@AuraEnabled
	public String totalOperativeCost { get; set; }
	@AuraEnabled
	public String totalSalesCost { get; set; }
	@AuraEnabled
	public String exwIncrementals { get; set; }
	@AuraEnabled
	public String finantialCost { get; set; }
	@AuraEnabled
	public String finantialCostRate { get; set; }
	@AuraEnabled
	public String exwFinancialCost { get; set; }
	@AuraEnabled
	public String marginBrute { get; set; }
	@AuraEnabled
	public String marginBruteNetSales { get; set; }
	@AuraEnabled
	public String overhead { get; set; }
	@AuraEnabled
	public String marginBeforeTaxes { get; set; }
	@AuraEnabled
	public String ptu { get; set; }
	@AuraEnabled
	public String isr { get; set; }
	@AuraEnabled
	public String netMargin { get; set; }
	@AuraEnabled
	public String incrementalCost { get; set; }
	@AuraEnabled
	public String incrementalCostCalc { get; set; }
	@AuraEnabled
	public String netMarginAboutNetSales { get; set; }
	@AuraEnabled
	public String movement { get; set; }
	@AuraEnabled
	public String marginManufactured { get; set; }
	@AuraEnabled
	public String labAlmex { get; set; }
	@AuraEnabled
	public String mxpMt { get; set; }
	@AuraEnabled
	public String usdMt { get; set; }
	@AuraEnabled
	public String labClient { get; set; }
	@AuraEnabled
	public String currentCurrency { get; set; }
	@AuraEnabled
	public String convertionCurrency { get; set; }
	@AuraEnabled
	public String shippingCostsPerLotSize { get; set; }
	@AuraEnabled
	public String shippingCostsPerLotSizeF { get; set; }
	@AuraEnabled
	public String fleteDeSalidaAClienteOutbound { get; set; }
	@AuraEnabled
	public String sgALtC { get; set; }
	@AuraEnabled
	public String sgAKgC { get; set; }
	@AuraEnabled
	public String costoEstandarPC { get; set; }
	@AuraEnabled
	public String factorDeConversionKgC { get; set; }
	@AuraEnabled
	public String factorDeConversionC { get; set; }
	@AuraEnabled
	public String unidadDeMedidaC { get; set; }
	@AuraEnabled
	public String deliveryCurrency { get; set; }
	@AuraEnabled
	public String systemDeliveryCost { get; set; }
	@AuraEnabled
	public Boolean isOil { get; set; }
	@AuraEnabled
	public String monthVolume { get; set; }
	@AuraEnabled
	public String convertionPrice { get; set; }
	@AuraEnabled
	public String densidadMark20C { get; set; }
	@AuraEnabled
	public String volumenLtGalon { get; set; }
	@AuraEnabled
	public String transferStationCost { get; set; }
	@AuraEnabled
	public String literProductCost { get; set; }
	@AuraEnabled
	public String factor1Breakdown { get; set; }
	@AuraEnabled
	public String factor2Breakdown { get; set; }
	@AuraEnabled
	public String literOutput { get; set; }
	@AuraEnabled
	public String finalFreight { get; set; }
	@AuraEnabled
	public String freightAddition { get; set; }
	@AuraEnabled
	public String freightCost { get; set; }
}